name: Construir S M APK

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      - name: Instalar Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: '8.9'

      - name: Extraer proyecto
        run: ZIP=$(find . -maxdepth 1 -name "*.zip" | head -n 1)
               unzip -q "$ZIP" -d sm_project
      

      - name: Compilar APK
        working-directory: sm_project
        run: gradle assembleDebug

      - name: Guardar APK
        uses: actions/upload-artifact@v4
        with:
          name: SM-APK
          path: sm_project/app/build/outputs/apk/debug/app-debug.apk
